// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnY4lJ5Ybosh9qI68_K7Ksz5_SN332LEo',
    appId: '1:45725712601:web:891e15d0339f7c6cb9fec8',
    messagingSenderId: '45725712601',
    projectId: 'fir-76dd2',
    authDomain: 'fir-76dd2.firebaseapp.com',
    storageBucket: 'fir-76dd2.appspot.com',
    measurementId: 'G-PJQ3LLY8E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC60WgKcaQ0UQvPw-Xq67FHgolfFK0aXmY',
    appId: '1:45725712601:android:1fe430206e29c099b9fec8',
    messagingSenderId: '45725712601',
    projectId: 'fir-76dd2',
    storageBucket: 'fir-76dd2.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnY4lJ5Ybosh9qI68_K7Ksz5_SN332LEo',
    appId: '1:45725712601:web:93fc5ff147f51f8eb9fec8',
    messagingSenderId: '45725712601',
    projectId: 'fir-76dd2',
    authDomain: 'fir-76dd2.firebaseapp.com',
    storageBucket: 'fir-76dd2.appspot.com',
    measurementId: 'G-8RXDL53YFM',
  );
}
